import { useState } from "react";
import { Link, useLocation } from "wouter";
import { toast } from "sonner";
import { AlertCircle, ArrowLeft, BookOpen, Loader2 } from "lucide-react";
import { trpc } from "@/lib/trpc";
import { startLogin } from "@/const";

export default function AuthPage() {
  const [, navigate] = useLocation();
  const utils = trpc.useUtils();
  const [mode, setMode] = useState(new URLSearchParams(window.location.search).get("mode") === "signup" ? "signup" : "login");
  const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [password, setPassword] = useState("");
  const oauthError = new URLSearchParams(window.location.search).get("oauthError");
  const signup = trpc.auth.signup.useMutation({ onSuccess: async () => { await utils.auth.me.invalidate(); navigate("/dashboard"); }, onError: (e) => toast.error(e.message) });
  const login = trpc.auth.login.useMutation({ onSuccess: async () => { await utils.auth.me.invalidate(); navigate("/dashboard"); }, onError: (e) => toast.error(e.message) });
  const pending = signup.isPending || login.isPending;
  const submit = (e: React.FormEvent) => { e.preventDefault(); if (mode === "signup") signup.mutate({ name, email, password }); else login.mutate({ email, password }); };
  return <div className="glass-page page-enter min-h-screen px-6 py-8 text-slate-100"><Link href="/" className="inline-flex items-center gap-2 text-sm text-slate-400 hover:text-white"><ArrowLeft size={16} /> Back to home</Link><div className="mx-auto flex max-w-md flex-col justify-center py-16"><div className="mb-8 flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-[#315e96]"><BookOpen size={20} /></div><span className="font-semibold">booklight</span></div><div className="glass-card rounded-3xl p-7 shadow-2xl"><h1 className="text-2xl font-semibold">{mode === "signup" ? "Create your account" : "Welcome back"}</h1><p className="mt-2 text-sm text-slate-500">{mode === "signup" ? "Start your next reading chapter." : "Pick up where you left off."}</p>{oauthError && <div role="alert" className="mt-5 flex gap-3 rounded-2xl border border-amber-200/20 bg-amber-200/10 p-3 text-sm text-amber-100"><AlertCircle size={18} className="mt-0.5 shrink-0" /><span>We couldn't complete that sign-in. Please try OAuth again or use email and password.</span></div>}<form onSubmit={submit} className="mt-7 space-y-4">{mode === "signup" && <label className="block text-sm text-slate-300">Name<input required value={name} onChange={(e) => setName(e.target.value)} className="mt-2 h-11 w-full rounded-xl border border-white/10 bg-black/20 px-3 outline-none focus:border-blue-300/60" /></label>}<label className="block text-sm text-slate-300">Email<input required type="email" value={email} onChange={(e) => setEmail(e.target.value)} className="mt-2 h-11 w-full rounded-xl border border-white/10 bg-black/20 px-3 outline-none focus:border-blue-300/60" /></label><label className="block text-sm text-slate-300">Password<input required minLength={mode === "signup" ? 8 : 1} type="password" value={password} onChange={(e) => setPassword(e.target.value)} className="mt-2 h-11 w-full rounded-xl border border-white/10 bg-black/20 px-3 outline-none focus:border-blue-300/60" /></label><button disabled={pending} className="glass-button flex h-11 w-full items-center justify-center gap-2 font-semibold disabled:opacity-60">{pending && <Loader2 className="animate-spin" size={16} />}{mode === "signup" ? "Create account" : "Sign in"}</button></form><div className="my-5 flex items-center gap-3 text-xs text-slate-600"><span className="h-px flex-1 bg-white/10" />or<span className="h-px flex-1 bg-white/10" /></div><button onClick={() => startLogin()} className="glass-button-secondary h-11 w-full text-sm">Continue with Manus OAuth</button><button onClick={() => setMode(mode === "signup" ? "login" : "signup")} className="mt-5 w-full text-sm text-blue-300 hover:text-white">{mode === "signup" ? "Already have an account? Sign in" : "New to Booklight? Create an account"}</button></div></div></div>;
}
