import { useEffect, useState } from "react";
import { toast } from "sonner";
import { Award, BookOpen, Save } from "lucide-react";
import { trpc } from "@/lib/trpc";
import { useAuth } from "@/_core/hooks/useAuth";

export default function Profile() {
  const { user } = useAuth(); const [name, setName] = useState(user?.name ?? ""); const [email, setEmail] = useState(user?.email ?? "");
  useEffect(() => { if (user) { setName(user.name ?? ""); setEmail(user.email ?? ""); } }, [user]);
  const history = trpc.library.borrow.myHistory.useQuery(); const badges = trpc.library.profile.badges.useQuery();
  const update = trpc.library.profile.update.useMutation({ onSuccess: () => toast.success("Profile updated"), onError: (e) => toast.error(e.message) });
  return <div className="page-enter"><div className="text-xs uppercase tracking-[.2em] text-blue-300">Account</div><h1 className="mt-2 text-3xl font-semibold text-white">Your profile</h1><p className="mt-2 text-sm text-slate-500">Keep your identity and reading history up to date.</p><div className="mt-7 grid gap-5 lg:grid-cols-[1fr_1fr]"><section className="glass-card rounded-2xl p-6"><h2 className="font-semibold text-white">Personal details</h2><div className="mt-5 space-y-4"><label className="block text-sm text-slate-300">Name<input value={name} onChange={(e) => setName(e.target.value)} className="mt-2 h-11 w-full rounded-xl border border-white/10 bg-black/20 px-3 outline-none" /></label><label className="block text-sm text-slate-300">Email<input type="email" value={email} onChange={(e) => setEmail(e.target.value)} className="mt-2 h-11 w-full rounded-xl border border-white/10 bg-black/20 px-3 outline-none" /></label><button onClick={() => update.mutate({ name, email })} className="flex items-center gap-2 rounded-xl bg-blue-400 px-4 py-2.5 text-sm font-semibold text-slate-950"><Save size={15} /> Save changes</button></div></section><section className="glass-card rounded-2xl p-6"><div className="flex items-center justify-between"><h2 className="font-semibold text-white">Badges earned</h2><Award className="text-amber-300" size={19} /></div><div className="mt-5 space-y-3">{badges.data?.length ? badges.data.map(({ badge }) => <div key={badge.id} className="flex items-center gap-3 rounded-xl bg-white/[.04] p-3"><div className="grid h-9 w-9 place-items-center rounded-full bg-amber-300/15 text-amber-200">✦</div><div><div className="text-sm text-slate-200">{badge.name}</div><div className="text-xs text-slate-500">{badge.description}</div></div></div>) : <p className="text-sm text-slate-500">Complete reading goals to earn badges.</p>}</div></section></div><section className="mt-5 glass-card rounded-2xl p-6"><div className="flex items-center gap-2"><BookOpen size={18} className="text-blue-300" /><h2 className="font-semibold text-white">Borrow history</h2></div><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[600px] text-left text-sm"><thead className="text-xs uppercase tracking-[.15em] text-slate-600"><tr><th className="py-3">Book</th><th>Status</th><th>Borrowed</th><th>Due</th><th>Fine</th></tr></thead><tbody>{history.data?.map(({ record, book }) => <tr key={record.id} className="border-t border-white/10 text-slate-300"><td className="py-3">{book.title}</td><td>{record.status}</td><td>{new Date(record.borrowDate).toLocaleDateString()}</td><td>{new Date(record.dueDate).toLocaleDateString()}</td><td>${(record.fineAmount / 100).toFixed(2)}</td></tr>)}</tbody></table>{!history.data?.length && <p className="py-6 text-sm text-slate-500">No borrow history yet.</p>}</div></section></div>;
}
