import { useState } from "react";
import { toast } from "sonner";
import { Users, Plus } from "lucide-react";
import { trpc } from "@/lib/trpc";

export default function Rooms() {
  const utils = trpc.useUtils();
  const rooms = trpc.library.readingRooms.list.useQuery(); const [name, setName] = useState(""); const [bookId, setBookId] = useState(""); const [startDate, setStartDate] = useState(""); const [endDate, setEndDate] = useState("");
  const create = trpc.library.readingRooms.create.useMutation({ onSuccess: async () => { toast.success("Reading room created"); setName(""); await utils.library.readingRooms.list.invalidate(); }, onError: (e) => toast.error(e.message) });
  const join = trpc.library.readingRooms.join.useMutation({ onSuccess: async () => { toast.success("Joined room"); await utils.library.readingRooms.list.invalidate(); }, onError: (e) => toast.error(e.message) });
  return <div><div className="flex items-end justify-between gap-4"><div><div className="text-xs uppercase tracking-[.2em] text-blue-300">Social reading</div><h1 className="mt-2 text-3xl font-semibold text-white">Reading rooms</h1><p className="mt-2 text-sm text-slate-500">Make a shared challenge around a book you care about.</p></div><Users className="text-blue-300" /></div><div className="mt-7 grid gap-5 lg:grid-cols-[1fr_1.4fr]"><form onSubmit={(e) => { e.preventDefault(); create.mutate({ name, bookId: Number(bookId), startDate, endDate }); }} className="rounded-2xl border border-white/10 bg-[#101a2b]/70 p-5"><h2 className="font-semibold text-white">Create a room</h2><div className="mt-4 space-y-3"><input required value={name} onChange={(e) => setName(e.target.value)} placeholder="Room name" className="h-10 w-full rounded-lg border border-white/10 bg-black/20 px-3 text-sm" /><input required type="number" value={bookId} onChange={(e) => setBookId(e.target.value)} placeholder="Book ID" className="h-10 w-full rounded-lg border border-white/10 bg-black/20 px-3 text-sm" /><div className="grid grid-cols-2 gap-3"><input required type="date" value={startDate} onChange={(e) => setStartDate(e.target.value)} className="h-10 rounded-lg border border-white/10 bg-black/20 px-3 text-sm text-slate-400" /><input required type="date" value={endDate} onChange={(e) => setEndDate(e.target.value)} className="h-10 rounded-lg border border-white/10 bg-black/20 px-3 text-sm text-slate-400" /></div><button className="flex h-10 w-full items-center justify-center gap-2 rounded-lg bg-blue-400 text-sm font-semibold text-slate-950"><Plus size={15} /> Create room</button></div></form><div className="space-y-3">{rooms.data?.map(({ room, book, memberCount }) => <div key={room.id} className="flex items-center gap-4 rounded-2xl border border-white/10 bg-[#0e141e]/80 p-4"><div className="grid h-12 w-12 place-items-center rounded-xl bg-gradient-to-br from-violet-300 to-indigo-700"><BookIcon /></div><div className="min-w-0 flex-1"><h3 className="truncate font-medium text-white">{room.name}</h3><p className="mt-1 text-xs text-slate-500">{book.title} · {new Date(room.startDate).toLocaleDateString()} → {new Date(room.endDate).toLocaleDateString()} · {memberCount} member{Number(memberCount) === 1 ? "" : "s"}</p></div><button onClick={() => join.mutate({ roomId: room.id })} className="rounded-lg border border-blue-300/30 px-3 py-2 text-xs text-blue-200 hover:bg-blue-400/10">Join</button></div>)}</div></div></div>;
}
function BookIcon() { return <span className="text-white">✦</span>; }
