import { eq } from "drizzle-orm";
import { books } from "../drizzle/schema";
import { getDb } from "../server/db";

const editions = [
  {
    id: 1,
    totalPages: 4,
    keyPoints: "The choices we avoid still shape our lives.\nSmall acts of attention can open new possibilities.\nThe reader is invited to reflect before rushing to the next answer.",
    content: `Reader demo edition — an original companion text inspired by themes of possibility, regret, and hope.\n\nAt midnight, the library was quiet enough for Nora to hear the shelves settling. Each book carried a different version of an ordinary life: not a prophecy, not a command, but an invitation to look again at the road behind her. She ran one finger along the spines and noticed that the dust did not feel old. It felt patient.\n\nShe opened a volume at random. The first page did not tell her what would happen. It asked a gentler question: what would you notice if you stopped measuring your life only by its endings? Nora read the line twice. Beyond the tall windows, the town was dark, yet the room seemed to hold its own dawn.\n\n---\n\nThe next morning arrived without a trumpet. A cup cracked in the kitchen. A bus arrived late. Someone laughed in the stairwell. The world had not changed its rules, but Nora had begun to see the spaces between them. She wrote three possibilities in the margin of a notebook, not because she believed each would come true, but because naming them made them less frightening.\n\nOne possibility was quiet: learn a skill, call a friend, walk home by a different street. Another was difficult: apologize without asking to be forgiven immediately. The last was bright and almost embarrassing: make something simply because making it felt alive. She folded the page and carried it with her.\n\n---\n\nIn the library, the books did not erase consequences. They made consequences visible. A life could be changed by a grand decision, but it could also be redirected by a repeated kindness. Nora began to understand that the best version of a life was not a perfect version. It was a life in which attention returned, again and again, to what mattered.\n\nShe placed the notebook beside the lamp. The page stayed blank after the three possibilities, ready for the next ordinary choice.\n\n---\n\nWhen the clock reached midnight, Nora closed the book. She did not leave with certainty. She left with a little more courage to be present in the life already in front of her. At the door she turned back, and the library lights warmed the shelves like small windows.\n\nThe last lesson was simple enough to carry: possibility is not a promise that every road will be easy. It is permission to take the next honest step.`
  },
  {
    id: 2,
    totalPages: 4,
    keyPoints: "Curiosity is a practical survival skill.\nGood teams treat uncertainty as information, not embarrassment.\nCareful observation turns a distant problem into a solvable sequence.",
    content: `Reader demo edition — an original companion text about curiosity, teamwork, and solving problems far from home.\n\nThe first signal arrived as a single green line on the navigation screen. It was too regular to be noise and too faint to be a message. Mara called the crew to the observation deck, where the ship moved through a field of silent ice. Nobody spoke for a moment. They watched the line return at exactly the same interval.\n\n“Measure it before naming it,” said Elias. He was the oldest member of the crew and the least impressed by dramatic explanations. Mara recorded the pulse, the temperature, and the ship’s orientation. A mystery became a list of observations. The list did not make the unknown smaller, but it gave the team somewhere to stand.\n\n---\n\nThey divided the work. One person checked the instruments. Another compared the signal with old flight records. Mara and Elias built a small model from the data, using colored threads to map the pulse against the ship’s movement. When the model was wrong, they marked the error in red instead of hiding it.\n\nBy the third hour they noticed a pattern: the signal was strongest whenever the ship passed behind a narrow band of ice. The band was not broadcasting. It was reflecting a source hidden beyond it. The discovery was modest, but the crew celebrated anyway. Progress often looked like a better question.\n\n---\n\nThe reflected signal led them to a drifting research buoy. Its power cell was low, but its archive was intact. Inside were observations from a mission that had ended years earlier. The buoy had been waiting, not for rescue exactly, but for someone patient enough to notice the rhythm of its call.\n\nMara copied the archive and repaired the transmitter with a spare circuit. The work took longer than expected because every shortcut created a new problem. Elias reminded the crew that a careful repair was not a slow repair. It was a repair that gave the future fewer surprises.\n\n---\n\nWhen the ship turned toward home, the green line disappeared from the screen. The crew kept the buoy’s archive in three places and wrote a clear report for the next team. They recorded not only the final answer but the failed guesses that had made the answer possible.\n\nFar from home, knowledge was a form of shelter. It was built by people who observed honestly, shared credit, and stayed curious after the first explanation failed.`
  },
  {
    id: 3,
    totalPages: 4,
    keyPoints: "Community makes room for both laughter and grief.\nQuestions become useful when people ask them with care.\nA small shared ritual can reconnect a neighborhood.",
    content: `Reader demo edition — an original companion mystery about friendship, memory, and the clues hidden in ordinary places.\n\nThe envelope was waiting beneath the brass bowl at the community hall. It had no stamp, no address, and one sentence written in blue ink: “Look for the missing Thursday.” Priya read it aloud to the three friends who had come to set tables for the neighborhood supper. They laughed first, because a mystery was easier to handle as a joke. Then they looked at one another and remembered that the hall calendar did, in fact, skip from Wednesday to Friday.\n\nThe missing page had not been torn. It had been removed neatly, leaving two pale squares where the tape had held it. Priya photographed the marks. Len checked the storage cupboard. Mo asked the caretaker whether anyone had borrowed the calendar. Each answer opened a smaller question.\n\n---\n\nThe search moved through ordinary places: the noticeboard, the kitchen drawer, the lost-and-found box. They found a red scarf, a broken stopwatch, and a recipe written in a hand nobody recognized. The recipe called for seven lemons and a pinch of smoked salt. At the bottom, someone had added a date: Thursday, 14 October.\n\nThat date belonged to the year the old bridge closed. The neighborhood had gathered in the hall then, sharing food while the river rose. Len remembered his mother singing to keep the children calm. Mo remembered a stranger offering his coat. Priya remembered only the smell of lemons. The clue had become a memory, and the memory had become a room full of people.\n\n---\n\nBehind the stage they found a wooden box containing photographs and handwritten menus from past suppers. The missing Thursday had been a community tradition: one evening each autumn when everyone brought a dish connected to someone they missed. The tradition had stopped after the bridge reopened. No one could say exactly why.\n\nThe envelope was not an accusation. It was an invitation to begin again. The friends placed the box on a table and wrote a new notice for the hall. They left the mystery unresolved in one small way: nobody knew who had placed the envelope.\n\n---\n\nOn the following Thursday, the hall filled before sunset. There were seven lemon cakes, three bowls of soup, and a great deal of laughter. A child found the blue pen beneath the stage and announced that the culprit must be nearby.\n\nPriya looked at the crowded room and decided that some mysteries were solved not by identifying one person, but by restoring what had been lost between people. The calendar received a new page. This time, nobody left the Thursday blank.`
  }
];

const db = await getDb();
if (!db) throw new Error("Database unavailable");
for (const edition of editions) {
  await db.update(books).set({ content: edition.content, keyPoints: edition.keyPoints, totalPages: edition.totalPages }).where(eq(books.id, edition.id));
}
console.log(`Seeded ${editions.length} original reader demo editions.`);
